export const API_PROVIDER_TOKENS = {
  CREATE_PROJECT_USE_CASE: Symbol('CREATE_PROJECT_USE_CASE'),
  UPDATE_PROJECT_USE_CASE: Symbol('UPDATE_PROJECT_USE_CASE'),
  DELETE_PROJECT_USE_CASE: Symbol('DELETE_PROJECT_USE_CASE'),
} as const;
