export const API_PROVIDER_TOKENS = {
  CREATE_PROJECT_USE_CASE: Symbol('CREATE_PROJECT_USE_CASE'),
  UPDATE_PROJECT_USE_CASE: Symbol('UPDATE_PROJECT_USE_CASE'),
  DELETE_PROJECT_USE_CASE: Symbol('DELETE_PROJECT_USE_CASE'),
  GET_PROJECT_USE_CASE: Symbol('GET_PROJECT_USE_CASE'),
  LIST_PROJECTS_USE_CASE: Symbol('LIST_PROJECTS_USE_CASE'),
  CREATE_TASK_USE_CASE: Symbol('CREATE_TASK_USE_CASE'),
  LIST_TASKS_USE_CASE: Symbol('LIST_TASKS_USE_CASE'),
  UPDATE_TASK_USE_CASE: Symbol('UPDATE_TASK_USE_CASE'),
  DELETE_TASK_USE_CASE: Symbol('DELETE_TASK_USE_CASE'),
  GET_TASK_USE_CASE: Symbol('GET_TASK_USE_CASE'),
  GET_PROJECT_SUMMARY_USE_CASE: Symbol('GET_PROJECT_SUMMARY_USE_CASE'),
} as const;
